### PR TITLE
feat: Added default format flag 

### PR DESCRIPTION
**Pull request by anisatahlil**
Issue #, if available: 

**Description of Changes**

[//]: #  (A description of the change that you made and the new user experience that it creates)
Implemented the default format flag option to allow the user to set a default format for output.  By setting the flag --defaultFormat, the user updates the configuration to hold this new default format. In the subsequent commands, the default format stored in the config will be used to format the output.

**Description of how you validated changes**
```
$ agc configure describe
2021-11-08T16:07:26-08:00 𝒊  Reading user specific configuration
CONFIG
FORMAT	text
USER	atahlil@amazon.com	atahlil3HYhj7
$ agc context list --defaultFormat=table
2021-11-08T16:07:41-08:00 𝒊  Listing contexts.
Name		EngineName
myContext	cromwell
spotCtx		cromwell
$ agc context list --format=text
2021-11-08T16:07:51-08:00 𝒊  Listing contexts.
CONTEXTSUMMARY	cromwell	myContext
CONTEXTSUMMARY	cromwell	spotCtx
$ agc context list
2021-11-08T16:08:00-08:00 𝒊  Listing contexts.
Name		EngineName
myContext	cromwell
spotCtx		cromwell
```

[//]: #  (A description of you validated your changes and any relevant logs that show your change works)

**Checklist**

- [x] If this change would make any existing documentation invalid, I have included those updates within this PR
- [x] I have added unit tests that prove my fix is effective or that my feature works
- [x] I have linted my code before raising the PR
- [x] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by elliot-smith** [comment]
Hi Anisata,
Appreciate the work you have done here but is it possible to add this to the "configure" command instead of overloading every command with a new setting (i.e. add a new command called "configure output" which sets the output to either tabular or table depending on the value you pass through)?

**Comment by anisatahlil** [comment]
> Hi Anisa, Appreciate the work you have done here but is it possible to add this to the "configure" command instead of overloading every command with a new setting (i.e. add a new command called "configure output" which sets the output to either tabular or table depending on the value you pass through)?

Thank you for the feedback. I had the same concern of overloading the root command by adding another flag but wanted to get some feedback before implementing it in a different way. I like the idea of a separate configure output command

**Comment by markjschreiber** [comment]
> > Hi Anisa, Appreciate the work you have done here but is it possible to add this to the "configure" command instead of overloading every command with a new setting (i.e. add a new command called "configure output" which sets the output to either tabular or table depending on the value you pass through)?
> 
> Thank you for the feedback. I had the same concern of overloading the root command by adding another flag but wanted to get some feedback before implementing it in a different way. I like the idea of a separate configure output command

Why not implement this as a new sub-command? Something like: `agc configure format`. You could use the code for `agc configure email` as an example `packages/cli/internal/pkg/cli/configure_email.go`

**Comment by anisatahlil** [comment]
> > > Hi Anisa, Appreciate the work you have done here but is it possible to add this to the "configure" command instead of overloading every command with a new setting (i.e. add a new command called "configure output" which sets the output to either tabular or table depending on the value you pass through)?
> > 
> > 
> > Thank you for the feedback. I had the same concern of overloading the root command by adding another flag but wanted to get some feedback before implementing it in a different way. I like the idea of a separate configure output command
> 
> Why not implement this as a new sub-command? Something like: `agc configure format`. You could use the code for `agc configure email` as an example `packages/cli/internal/pkg/cli/configure_email.go`

I have created a different pull request to show this work. I have implemented it as `agc configure format`. I will close this pull request

**Pull request closed without merging**
