### PR TITLE
refactor: Opensourcing containers for Cromwell, Nextflow, MiniWDL engines

### PR DESCRIPTION
**Pull request by AndreyDovydenko**
Issue #, if available:

**Description of Changes**

I've moved existing docker containers for Cromwell, Nextflow, MiniWDL engines into our github mono repo, all the changes in the conatiners and buildspecs are purely for the sake of building process to work with the mono repo setup now, there's no functional difference in between then and now. 

**Description of how you validated changes**

I've deployed our CICD pipeline into own AWS account and picked the sources from my github account to verify everything is buildable and publishable before opening up a pull request with this change.

**Checklist**

- [ ] If this change would make any existing documentation invalid, I have included those updates within this PR
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] I have linted my code before raising the PR
- [x] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ghawk1ns** [comment]
running `make init` and committing the changes will get the `ci / build` check to pass

**Comment by AndreyDovydenko** [comment]
> running `make init` and committing the changes will get the `ci / build` check to pass

i wonder why that's required given i haven't touched any golang code?

**Review by tneely — CHANGES_REQUESTED** [review]
Looks like you accidentally commited the docsy submodule. We should probably add it to our `.gitignore`

**Comment by AndreyDovydenko** [comment]
> Looks like you accidentally commited the docsy submodule. We should probably add it to our `.gitignore`

i think the diff is showing the changes from within the submodule itself, we have referenced docsy in 

```
[submodule "site/themes/docsy"]
	path = site/themes/docsy
	url = https://github.com/google/docsy.git
```

**Comment by AndreyDovydenko** [comment]
> > Looks like you accidentally commited the docsy submodule. We should probably add it to our `.gitignore`
> 
> i think the diff is showing the changes from within the submodule itself, we have referenced docsy in
> 
> ```
> [submodule "site/themes/docsy"]
> 	path = site/themes/docsy
> 	url = https://github.com/google/docsy.git
> ```

https://stackoverflow.com/questions/5033441/where-does-git-store-the-sha1-of-the-commit-for-a-submodule - helped me figure this out.

**Review by tneely — APPROVED** [review]

**Review by ghawk1ns — APPROVED** [review]

**Pull request merged**
